apiVersion: v1
kind: Service
metadata:
  name: prediction-cp-service
  labels:
    app: prediction-cp
  namespace: fifaxgb
spec:
  type: LoadBalancer
  ports:
  - port: 5003
    targetPort: 5000
  selector:
    app: prediction-cp