CREATE TABLE fifa (

    ID INT PRIMARY KEY,

    Name TEXT,
    Age INT,
    Value INT,
    Wage INT,
    Preferred_Foot TEXT,
    Weak_Foot INT,
    Trick_Skills INT,
    Work_Rate TEXT,
    Position TEXT,
    Jersey_Number INT,
    Contract_Valid_Until INT,
    Height INT,
    Weight INT,
    Striker INT,
    CentralMidFielder INT,
    SideMidFielder INT,
    WingBack INT,
    CenterBack INT,
    Crossing INT,
    Finishing INT,
    HeadingAccuracy INT,
    ShortPassing INT,
    Volleys INT,
    Dribbling INT,
    Curve INT,
    FreeKickAccuracy INT,
    LongPassing INT,
    BallControl INT,
    Acceleration INT,
    SprintSpeed INT,
    Agility INT,
    Reactions INT,
    ShotPower INT,
    Jumping INT,
    Stamina INT,
    Strength INT,
    LongShots INT,
    Aggression INT,
    Interceptions INT,
    Positioning INT,
    Vision INT,
    Penalties INT,
    Composure INT,
    Marking INT,
    StandingTackle INT,
    SlidingTackle INT,
    Work_Rate_A TEXT,
    Work_Rate_D TEXT,
    Position_cat INT,
    Basic_Player INT,
    Position_Stat INT
);