apiVersion: v1
kind: Service
metadata:
  name: prediction-cp-service
  labels:
    app: prediction-cp
  namespace: myapps
spec:
  type: LoadBalancer
  ports:
  - port: 5002
    targetPort: 5000
  selector:
    app: prediction-cp