apiVersion: v1
kind: Service
metadata:
  name: training-cp-service
  labels:
    app: training-cp
  namespace: myapps
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5000
  selector:
    app: training-cp